### ISSUE TITLE
after nuget install opencvsharp 2.0.4666.42387, still can not find class Window and VideoCapture and Cv2 

### ISSUE THREAD

**Issue by killaragorn** [qaisbayabani/SCRCPY-C-Sharp-Client#3]
Hello, I installed opencvshrp using nuget according to your requirements, but it still fails to compile, because I can’t find window, Cv2, and VideoCapture. Can you help me a little bit?

environment：
vs 2019 version 16.11.0
opencvsharp version 2.0.4666.42387
![image](https://user-images.githubusercontent.com/67131511/129535381-75ca1081-62f4-4762-ad32-b07b2609264b.png)

**Comment by qaisbayabani** [comment]
dear sory for late response its only instalation related issue your soft nuget is not instaled correctly or added to your project so the IDE is not recognizing the command and marked red line under.

**Comment by qaisbayabani** [comment]
> Hello, I installed opencvshrp using nuget according to your requirements, but it still fails to compile, because I can’t find window, Cv2, and VideoCapture. Can you help me a little bit?
> 
> environment：
> vs 2019 version 16.11.0
> opencvsharp version 2.0.4666.42387
> ![image](https://user-images.githubusercontent.com/67131511/129535381-75ca1081-62f4-4762-ad32-b07b2609264b.png)

**Comment by qaisbayabani** [comment]
![123](https://user-images.githubusercontent.com/25330219/130419978-660638d2-96ef-42e0-ac6d-e8e61c51668e.jpg)

**Comment by qaisbayabani** [comment]
instal with MS Visual Studio default NUGet Manager

**Comment by qaisbayabani** [comment]
i have 4.x version as u can c

**Comment by killaragorn** [comment]
Thanks for replying! The problem has been solved. Thank you very much
